#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme

title: civitas.world docs
description: documentation for the civitas.world game servers and community
logo: /images/laurel_earth.png

show_downloads: false

theme: jekyll-theme-hacker